title: New Super Cool Indie Site 
description: A new and very rad site
theme: just-the-docs

url: https://rednoseeng.github.io/indieexperiment

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

search_enabled: false

favicon_ico: "/assets/images/favicon.ico"
